# Generated by Django 4.1.7 on 2023-02-16 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('cName', models.CharField(max_length=20)),
                ('age', models.FloatField()),
            ],
        ),
    ]
